const artPlaceholderImages = {
    2: "/assets/art/placeholders/2.jpg",
    3: "/assets/art/placeholders/3.jpg",
    4: "/assets/art/placeholders/4.jpg",
    5: "/assets/art/placeholders/5.jpg",
    6: "/assets/art/4-angled-placeholder.jpg",
    7: "/assets/art/placeholders/7.jpg",
    8: "/assets/art/placeholders/8.jpg",
    9: "/assets/art/placeholders/9.jpg",
    10: "/assets/art/placeholders/10.jpg",
    11: "/assets/art/placeholders/11.jpg",
    12: "/assets/art/placeholders/12.jpg",
    13: "/assets/art/placeholders/13.jpg",
    14: "/assets/art/placeholders/14.jpg",
    15: "/assets/art/placeholders/15.jpg",
    16: "/assets/art/placeholders/16.jpg",
    17: "/assets/art/placeholders/17.jpg",
    18: "/assets/art/placeholders/18.jpg",
    19: "/assets/art/placeholders/19.jpg",
    20: "/assets/art/placeholders/20.jpg",
    21: "/assets/art/placeholders/21.jpg",
    22: "/assets/art/placeholders/22.jpg",
    23: "/assets/art/placeholders/23.jpg",
    24: "/assets/art/placeholders/24.jpg",
    26: "/assets/art/placeholders/26.jpg",
    27: "/assets/art/placeholders/27.jpg",
    28: "/assets/art/placeholders/28.jpg",
    29: "/assets/art/placeholders/29.jpg",
    30: "/assets/art/placeholders/30.jpg",
};

export default artPlaceholderImages;
