const artZoomImages = {
    2: "/assets/art/zoom/2.jpg",
    3: "/assets/art/zoom/3.jpg",
    4: "/assets/art/zoom/4.jpg",
    5: "/assets/art/zoom/5.jpg",
    6: "/assets/art/zoom/44.jpg",
    7: "/assets/art/zoom/7.jpg",
    8: "/assets/art/zoom/8.jpg",
    9: "/assets/art/zoom/9.jpg",
    10: "/assets/art/zoom/10.jpg",
    11: "/assets/art/zoom/11.jpg",
    12: "/assets/art/zoom/12.jpg",
    13: "/assets/art/zoom/13.jpg",
    15: "/assets/art/zoom/15.jpg",
    16: "/assets/art/zoom/16.jpg",
    17: "/assets/art/zoom/17.jpg",
    18: "/assets/art/zoom/18.jpg",
    19: "/assets/art/zoom/19.jpg",
    20: "/assets/art/zoom/20.jpg",
    21: "/assets/art/zoom/21.jpg",
    22: "/assets/art/zoom/22.jpg",
    23: "/assets/art/zoom/23.jpg",
    24: "/assets/art/zoom/24.jpg",
    26: "/assets/art/zoom/26.jpg",
    27: "/assets/art/zoom/27.jpg",
    28: "/assets/art/zoom/28.jpg",
    29: "/assets/art/zoom/29.jpg",
};

export default artZoomImages;
